const baseUrlAPI = "http://localhost:3408"
export const UserResourceUrl = `${baseUrlAPI}/api/Users`
export const ProductResourceUrl = `${baseUrlAPI}/api/Products`
export const CategoryResourceUrl = `${baseUrlAPI}/api/Categories`
export const UserProductResourceUrl = `${baseUrlAPI}/api/UserProducts`

export const TAB_USER = 'tab_user'
export const TAB_PRODUCT = 'tab_product'
export const TAB_CATEGORY = 'tab_category'
export const CHANGE_TAB = 'CHANGE_TAB'

export const FETCH_LIST_PRODUCTS = 'FETCH_LIST_PRODUCTS'
export const FETCH_LIST_USERS = 'FETCH_LIST_USERS'
export const FETCH_LIST_CATEGORIES = 'FETCH_LIST_CATEGORIES'
export const FETCH_LIST_OPTION_CATEGORIES = 'FETCH_LIST_OPTION_CATEGORIES'

export const STARTING_ADD_NEW_USER = "STARTING_ADD_NEW_USER"
export const STARTING_EDIT_USER = "STARTING_EDIT_USER"

export const STARTING_ADD_NEW_PRODUCT = "STARTING_ADD_NEW_PRODUCT"
export const STARTING_EDIT_PRODUCT = "STARTING_EDIT_PRODUCT"

export const STARTING_ADD_NEW_CATEGORY = "STARTING_ADD_NEW_CATEGORY"
export const STARTING_EDIT_CATEGORY = "STARTING_EDIT_CATEGORY"
export const STARTING_DELETE_CATEGORY = "STARTING_DELETE_CATEGORY"

export const TOGGLE_DISPLAY_USER_DETAIL = "TOGGLE_DISPLAY_USER_DETAIL"
export const TOGGLE_DISPLAY_USER_NEW = "TOGGLE_DISPLAY_USER_NEW"
export const CHANGE_USER_NEW = "CHANGE_USER_NEW"

export const TOGGLE_DISPLAY_PRODUCT_NEW = "TOGGLE_DISPLAY_PRODUCT_NEW"
export const CHANGE_PRODUCT_NEW = "CHANGE_PRODUCT_NEW"

export const TOGGLE_DISPLAY_CATEGORY_NEW = "TOGGLE_DISPLAY_CATEGORY_NEW"
export const CHANGE_CATEGORY_NEW = "CHANGE_CATEGORY_NEW"

export const TOGGLE_DISPLAY_CATEGORY_EDIT = "TOGGLE_DISPLAY_CATEGORY_EDIT"
export const CHANGE_CATEGORY_EDIT = "CHANGE_CATEGORY_EDIT"

export const TOGGLE_DISPLAY_PRODUCT_EDIT = "TOGGLE_DISPLAY_PRODUCT_EDIT"
export const CHANGE_PRODUCT_EDIT = "CHANGE_PRODUCT_EDIT"

export const TOGGLE_DISPLAY_USER_EDIT = "TOGGLE_DISPLAY_USER_EDIT"
export const CHANGE_USER_EDIT = "CHANGE_USER_EDIT"
